python train_gen.py --categories modelnet_airplane --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_bathtub --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_bed --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_bench --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_bookshelf --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_bottle --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_bowl --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_car --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_chair --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_cone --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_cup --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_curtain --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_desk --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_door --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_dresser --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_flower_pot --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_glass_box --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_guitar --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_keyboard --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_lamp --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_laptop --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_mantel --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_monitor --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_night_stand --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_person --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_piano --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_plant --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_radio --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_range_hood --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_sink --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_sofa --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_stairs --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_stool --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_table --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_tent --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_toilet --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_tv_stand --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_vase --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_wardrobe --device cuda:2 --max_iters 32000
python train_gen.py --categories modelnet_xbox --device cuda:2 --max_iters 32000